retry yarn

diff --git a/azure-pipeline.nightly.yml b/azure-pipeline.nightly.yml
--- a/azure-pipeline.nightly.yml
+++ b/azure-pipeline.nightly.yml
@@ -23,7 +23,16 @@ extends:
   parameters:
     l10nSourcePaths: ./src
     buildSteps:
-      - script: yarn install --frozen-lockfile
+      - script: |
+          set -e
+          for i in {1..3}; do # try 3 times
+            yarn --frozen-lockfile --check-files && break
+            if [ $i -eq 3 ]; then
+              echo "Yarn failed too many times" >&2
+              exit 1
+            fi
+            echo "Yarn failed $i, trying again..."
+          done
         displayName: Install dependencies
 
       - script: yarn run bundle
